### ISSUE TITLE
A Question about `Continuous RI-EKF Equations'

### ISSUE THREAD

**Issue by rj-sujinglan** [RossHartley/invariant-ekf#5]
The IEKF system noise Qt=Adx*Cov (wt)*Adx^T .
where 
Adx=[R         0  0   0]
        [(vt)xR  R  0  0]
        [(pt)xR  0  R  0]
        [(dt)xR  0  0  R]
if  the position pt is large, for example the robot moves to a certain location (1000,1000,1000),and its velocity is (100,100,100) ,then Qt is very large. Namely IEKF's system noise is very large and this is unreasonable. Why is this happening?

**Comment by JzHuai0108** [comment]
Surprisingly, in a simulation of 100 seconds, propagating covariance from a small position and from a large position (1000, 1000, 1000) achieved similar performance when comparing the the final covariance relative to that of a reference propagation implemented with traditional error formulation.

**Comment by RossHartley** [comment]
The covariance that the InEKF estimates is different than the typical EKF. For example, the position block of the InEKF covariance matrix is not the covariance of the Euclidean position error.

Although the covariance values can appear large, they will likely be much smaller when it is transformed appropriately.

See equation 33 in https://arxiv.org/pdf/1904.09251.pdf
