### ISSUE TITLE
Has this repository compiled on Mac?

### ISSUE THREAD

**Issue by yuan0623** [RossHartley/invariant-ekf#8]
Has this repository compiled on Mac? I'm using Mac to compile this repository and I got following error message:clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../lib/libinekf.dylib] Error 1
make[1]: *** [CMakeFiles/inekf.dir/all] Error 2
make: *** [all] Error 2
I have installed the requirement package already.
Thanks in advance!

**Comment by RossHartley** [comment]
I have not tried compiling on Mac. This was only tested on Ubuntu 16.04.

**Comment by yuan0623** [comment]
Thank you so much. It runs perfectly on my Ubuntu 18.
